"""Slidevテストツール（LangChain Tool）

ハードコードされたSlidevスライドを生成し、PDF出力をテストする。
ReActエージェントから呼び出してSlidev動作確認を行う。

Phase 0（MVP検証用）:
- ハードコードされたマークダウン
- slidev export コマンドでPDF生成
- フロントエンドへのパス返却テスト
"""

from langchain_core.tools import tool
from typing import Optional
import json
from pathlib import Path
import subprocess
import shutil
import re

# 既存のmarp_agentからユーティリティ関数をインポート
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from marp_agent import _slugify_en


@tool
def generate_slidev_test(topic: str = "AI最新情報") -> str:
    """Slidevでテストスライドを生成（ハードコード版）

    ハードコードされたSlidevマークダウンからPDFスライドを生成。
    MVPとしてSlidev動作確認、フロントエンド統合テストに使用。

    処理フロー:
    1. ハードコードされたSlidevマークダウンを生成
    2. .mdファイルとして保存
    3. slidev export コマンドでPDF出力
    4. ファイルパスをJSON形式で返却

    Args:
        topic: スライドのトピック（デフォルト: "AI最新情報"）

    Returns:
        str: 生成されたスライドのパスと結果情報（JSON形式）
    """

    # モダンなデザインのSlidevマークダウン（拡張版）
    slide_content = f"""---
theme: apple-basic
highlighter: shiki
class: text-center
drawings:
  persist: false
fonts:
  sans: 'Inter'
  serif: 'Roboto Slab'
  mono: 'Fira Code'
---

# 🚀 {topic}
## 2025年10月版

<div class="pt-12">
  <span class="px-2 py-1 rounded" style="background: #007bff; color: white;">
    AI Industry Report
  </span>
</div>

---
layout: intro
class: text-left
---

## 📋 Agenda

<v-clicks>

- 🏢 **Microsoft AI** - エンタープライズAIの最前線
- 🤖 **OpenAI** - GPT-4 Turboの進化
- 🌟 **Google Gemini** - マルチモーダルAIの可能性
- 💡 **まとめ** - 今後の展望

</v-clicks>

---
layout: two-cols
class: px-2
---

## 🏢 Microsoft AI

<v-clicks>

- **Azure OpenAI Service**
  - GPT-4 Turbo 対応
  - エンタープライズグレード

- **Copilot Studio**
  - ノーコードAI開発
  - ビジネスプロセス統合

- **Semantic Kernel**
  - エージェント開発
  - プラグインエコシステム

</v-clicks>

::right::

<div class="flex items-center justify-center h-full">
  <div style="width: 300px; height: 200px; background: linear-gradient(135deg, #0078d4 0%, #00bcf2 100%); border-radius: 12px; display: flex; align-items: center; justify-content: center; color: white; font-size: 24px; font-weight: bold; box-shadow: 0 10px 30px rgba(0,0,0,0.2);">
    Azure AI
  </div>
</div>

---
layout: two-cols
---

## 🤖 OpenAI 最新情報

::left::

### GPT-4 Turbo

<v-clicks>

- ✅ コスト削減（前世代比50%）
- ✅ 128K context window
- ✅ JSON mode対応
- ✅ 2023年12月までの知識

</v-clicks>

::right::

### DALL-E 3

<v-clicks>

- 🎨 より高精度な画像生成
- 🧠 プロンプト理解向上
- 🔒 安全性フィルター強化
- 🌐 商用利用可能

</v-clicks>

---
layout: center
class: text-center
---

## 🌟 Google Gemini

<div class="grid grid-cols-3 gap-4 mt-8">

<div style="padding: 1rem; background: #e3f2fd; border-radius: 12px;">
  <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">🧠</div>
  <div style="font-weight: bold;">Gemini Pro</div>
  <div style="font-size: 0.875rem;">マルチモーダルAI</div>
</div>

<div style="padding: 1rem; background: #e8f5e9; border-radius: 12px;">
  <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">☁️</div>
  <div style="font-weight: bold;">Vertex AI統合</div>
  <div style="font-size: 0.875rem;">エンタープライズ向け</div>
</div>

<div style="padding: 1rem; background: #f3e5f5; border-radius: 12px;">
  <div style="font-size: 2.5rem; margin-bottom: 0.5rem;">🤝</div>
  <div style="font-weight: bold;">Duet AI</div>
  <div style="font-size: 0.875rem;">Workspace連携</div>
</div>

</div>

---
layout: end
class: text-center
---

# ✨ まとめ

<div class="mt-8">

## AI技術は急速に進化中 🚀

各社の最新情報をキャッチアップしましょう

</div>

<div style="position: absolute; bottom: 1.5rem; right: 1.5rem; font-size: 0.875rem; opacity: 0.5;">
  Generated by SlidePilot AI
</div>

"""

    try:
        # ファイル保存
        slide_dir = Path(__file__).parent.parent / "slides"
        slide_dir.mkdir(parents=True, exist_ok=True)

        # ファイル名生成
        slug = _slugify_en(topic) or "test"
        md_path = slide_dir / f"{slug}_slidev_test.md"
        md_path.write_text(slide_content, encoding="utf-8")

        # Slidev PDF出力
        pdf_path = slide_dir / f"{slug}_slidev_test.pdf"

        slidev = shutil.which("slidev")
        if slidev:
            try:
                # Slidev export コマンド
                subprocess.run(
                    ["slidev", "export", str(md_path),
                     "--output", str(pdf_path),
                     "--format", "pdf",
                     "--timeout", "60000"],  # 60秒タイムアウト
                    check=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    timeout=90  # プロセス全体のタイムアウト
                )

                # 絶対パスから相対パスに変換（frontend/publicからアクセス可能にする）
                relative_path = str(pdf_path.relative_to(slide_dir.parent))

                return json.dumps({
                    "status": "success",
                    "message": f"✅ Slidevスライドを生成しました: {pdf_path.name}",
                    "title": topic,
                    "slide_path": relative_path
                }, ensure_ascii=False)

            except subprocess.TimeoutExpired:
                relative_path = str(md_path.relative_to(slide_dir.parent))
                return json.dumps({
                    "status": "error",
                    "message": "⚠️ PDF生成がタイムアウトしました（90秒超過）",
                    "title": topic,
                    "slide_path": relative_path,
                    "error": "Playwright初回インストール中の可能性があります。もう一度お試しください。"
                }, ensure_ascii=False)

            except subprocess.CalledProcessError as e:
                # PDF生成失敗時はMDのみ返す
                error_msg = e.stderr.decode() if e.stderr else str(e)
                relative_path = str(md_path.relative_to(slide_dir.parent))
                return json.dumps({
                    "status": "partial",
                    "message": "⚠️ PDF生成に失敗しました。Markdownのみ保存しました。",
                    "title": topic,
                    "slide_path": relative_path,
                    "error": f"詳細: {error_msg}"
                }, ensure_ascii=False)
        else:
            # slidev未インストール時
            relative_path = str(md_path.relative_to(slide_dir.parent))
            return json.dumps({
                "status": "md_only",
                "message": "⚠️ slidevが見つかりません。Markdownのみ保存しました。",
                "title": topic,
                "slide_path": relative_path,
                "error": "slidevをインストールしてください: npm install -g slidev"
            }, ensure_ascii=False)

    except Exception as e:
        # 予期しないエラー
        return json.dumps({
            "status": "error",
            "message": f"❌ スライド生成例外: {str(e)}",
            "title": topic
        }, ensure_ascii=False)
